const QUESTIONS = [
{
    "question": "Který svátek slaví Češi i lidé po celém světě 8. března?",
    "options": { "A": "Den matek.", "B": "Den učitelů.", "C": "Mezinárodní den žen.", "D": "Mezinárodní den dětí." },
    "correct": "C"
  },
  {
    "question": "Kterou přílohu tradičně jedí Češi ke smaženému kaprovi v mnoha domácnostech na Štědrý večer?",
    "options": { "A": "Rýži.", "B": "Těstoviny.", "C": "Bramborový salát.", "D": "Houskové knedlíky." },
    "correct": "C"
  },
  {
    "question": "Kraslice je vejce, které se barví a zdobí. Kdy ženy a dívky dávají mužům kraslice?",
    "options": { "A": "Na Dušičky.", "B": "Na Nový rok.", "C": "Na Štědrý den.", "D": "Na Velikonoce." },
    "correct": "D"
  },
  {
    "question": "Který státní svátek se slaví v České republice na podzim?",
    "options": { "A": "Den obnovy samostatného českého státu.", "B": "Den boje za svobodu a demokracii.", "C": "Den upálení mistra Jana Husa.", "D": "Den vítězství." },
    "correct": "B"
  },
  {
    "question": "Velký pátek je svátek, který připomíná smrt Ježíše Krista. Ke kterému svátečnímu období patří Velký pátek?",
    "options": { "A": "K Velikonocům.", "B": "K Dušičkám.", "C": "K Vánocům.", "D": "K adventu." },
    "correct": "A"
  },
  {
    "question": "Památce zesnulých se v Česku lidově říká Dušičky. Je to den, kdy se podle české tradice zdobí hroby květinami, rozsvěcují se svíčky a vzpomíná se na zemřelé. Ve kterém období se slaví tento svátek?",
    "options": { "A": "Na jaře.", "B": "V létě.", "C": "Na podzim.", "D": "V zimě." },
    "correct": "C"
  },
  {
    "question": "Den české státnosti je také svátkem svatého Václava. Kníže Václav z rodu Přemyslovců je patronem Čech a Moravy. Kdy se slaví Den české státnosti?",
    "options": { "A": "V září.", "B": "V říjnu.", "C": "V dubnu.", "D": "V květnu." },
    "correct": "A"
  },
  {
    "question": "Který den si Češi obyčejně dávají vánoční dárky?",
    "options": { "A": "6. ledna.", "B": "24. prosince.", "C": "25. prosince.", "D": "26. prosince." },
    "correct": "B"
  },
  {
    "question": "Který z těchto svátků se připomíná v České republice v květnu?",
    "options": { "A": "Tři králové.", "B": "Svátek práce.", "C": "Vznik Československa.", "D": "Den boje za svobodu a demokracii." },
    "correct": "B"
  },
  {
    "question": "Jana dostala od Mikuláše, čerta a anděla balíček, ve kterém byla jablka, mandarinky, čokoláda, brambory a také drobné dárky. Kdy dostala Jana tento balíček?",
    "options": { "A": "6. ledna.", "B": "5. prosince.", "C": "24. prosince.", "D": "31. prosince." },
    "correct": "B"
  },
  {
    "question": "Při jízdě osobním autem mají řidič a spolujezdci podle zákona určité povinnosti. Co musí řidič a spolujezdec dodržovat?",
    "options": { "A": "Musí mít zapnuté pásy.", "B": "Musí mít zavřená přední okna.", "C": "Musí mít na sobě reflexní vesty.", "D": "Musí mít zamčené přední dveře." },
    "correct": "A"
  },
  {
    "question": "Paní Svobodová jezdí na kole do práce. Ve které situaci porušuje pravidla silničního provozu?",
    "options": { "A": "Jede na kole po chodníku.", "B": "Jede na kole po pravé straně silnice.", "C": "Jede na kole v řadě za svou kolegyní.", "D": "Jede na kole a dává rukou znamení o změně směru jízdy." },
    "correct": "A"
  },
  {
    "question": "Pan Svoboda chce řídit osobní automobil. Který typ řidičského průkazu potřebuje?",
    "options": { "A": "Řidičský průkaz skupiny A.", "B": "Řidičský průkaz skupiny B.", "C": "Řidičský průkaz skupiny C.", "D": "Řidičský průkaz skupiny D." },
    "correct": "B"
  },
  {
    "question": "Kolik piv s obsahem alkoholu může vypít řidič podle zákona při řízení auta v Česku?",
    "options": { "A": "Tři.", "B": "Dvě.", "C": "Jedno.", "D": "Žádné." },
    "correct": "D"
  },
  {
    "question": "Který dopravní prostředek má přednost před chodcem na přechodu?",
    "options": { "A": "Auto.", "B": "Tramvaj.", "C": "Autobus.", "D": "Motocykl." },
    "correct": "B"
  },
  {
    "question": "Paní Svobodová si koupila nový automobil. Které pojištění musí podle zákona uzavřít?",
    "options": { "A": "Povinné ručení.", "B": "Životní pojištění.", "C": "Úrazové pojištění.", "D": "Havarijní pojištění." },
    "correct": "A"
  },
  {
    "question": "Kdo má povinnost nosit podle zákona oblečení s reflexními prvky?",
    "options": { "A": "Osoba, která jde v noci v obci po chodníku.", "B": "Osoba, která jde ve dne v obci po chodníku.", "C": "Osoba, která jde v noci mimo obec po silnici.", "D": "Osoba, která jde ve dne mimo obec po silnici." },
    "correct": "C"
  },
  {
    "question": "V České republice je několik druhů dálničních známek, které se liší dobou platnosti. Který druh dálniční známky není možné koupit?",
    "options": { "A": "S platností 1 den.", "B": "S platností 10 dní.", "C": "S platností 30 dní.", "D": "S platností 90 dní." },
    "correct": "D"
  },
  {
    "question": "Od kolika let mohou jezdit děti po silnici na kole bez dohledu další osoby?",
    "options": { "A": "Od 3 let.", "B": "Od 6 let.", "C": "Od 10 let.", "D": "Od 18 let." },
    "correct": "C"
  },
  {
    "question": "Která z uvedených věcí patří k povinné výbavě osobního automobilu?",
    "options": { "A": "Rádio.", "B": "Lékárnička.", "C": "Destilovaná voda.", "D": "Nádoba na benzin." },
    "correct": "B"
  },
  {
    "question": "Paní Novotná vidí požár. Chce zavolat hasiče. Na které z těchto telefonních čísel zavolá?",
    "options": { "A": "150.", "B": "155.", "C": "156.", "D": "158." },
    "correct": "A"
  },
  {
    "question": "Které telefonní číslo má zdravotnická záchranná služba?",
    "options": { "A": "150.", "B": "155.", "C": "156.", "D": "158." },
    "correct": "B"
  },
  {
    "question": "Paní Svobodová není spokojená se svou zdravotní pojišťovnou. Jak často může změnit zdravotní pojišťovnu?",
    "options": { "A": "Jednou za měsíc.", "B": "Jednou za 3 měsíce.", "C": "Jednou za 6 měsíců.", "D": "Jednou za 12 měsíců." },
    "correct": "D"
  },
  {
    "question": "Pan Novák je nemocný. Omylem si smazal SMS s receptem na předepsané léky. Který doklad může pan Novák v lékárně předložit, aby dostal předepsané léky?",
    "options": { "A": "Rodný list.", "B": "Řidičský průkaz.", "C": "Očkovací průkaz.", "D": "Občanský průkaz." },
    "correct": "D"
  },
  {
    "question": "Integrovaný záchranný systém (IZS) se podílí na řešení mimořádných událostí a provádí záchranné práce. Co nepatří do Integrovaného záchranného systému (IZS) České republiky?",
    "options": { "A": "Policie ČR.", "B": "Krajské úřady ČR.", "C": "Hasičský záchranný sbor ČR.", "D": "Poskytovatelé záchranné zdravotnické služby ČR." },
    "correct": "B"
  },
  {
    "question": "Které telefonní číslo má jednotný záchranný systém (hasiči, policie, zdravotnická záchranná služba) ve všech státech Evropské unie?",
    "options": { "A": "112.", "B": "150.", "C": "911.", "D": "999." },
    "correct": "A"
  },
  {
    "question": "Od roku 2020 vystavují lékaři v České republice pouze elektronické neschopenky (doklad o pracovní neschopnosti). Které instituci lékař posílá elektronickou neschopenku?",
    "options": { "A": "Zdravotní pojišťovně.", "B": "Ministerstvu zdravotnictví.", "C": "Okresní hygienické stanici.", "D": "Okresní správě sociálního zabezpečení." },
    "correct": "D"
  },
  {
    "question": "Pan Novák viděl dopravní nehodu. Chce volat Policii České republiky. Které telefonní číslo použije?",
    "options": { "A": "150.", "B": "155.", "C": "156.", "D": "158." },
    "correct": "D"
  },
  {
    "question": "Pan Novotný je občanem České republiky, je nezaměstnaný a je registrovaný na úřadu práce jako uchazeč o zaměstnání. Kdo platí jeho povinné zdravotní pojištění?",
    "options": { "A": "Stát.", "B": "Finanční úřad.", "C": "Platí si ho sám.", "D": "Jeho poslední zaměstnavatel." },
    "correct": "A"
  },
  {
    "question": "Pan Svoboda ztratil průkaz pojištěnce zdravotní pojišťovny. Do kolika dnů musí nahlásit ztrátu zdravotní pojišťovně?",
    "options": { "A": "Do jednoho dne.", "B": "Do osmi dnů.", "C": "Do třiceti dnů.", "D": "Do šedesáti dnů." },
    "correct": "B"
  },
  {
    "question": "Z čeho se skládá jednotná přijímací zkouška na střední školy?",
    "options": { "A": "Z českého jazyka a dějepisu.", "B": "Z českého jazyka a zeměpisu.", "C": "Z českého jazyka a matematiky.", "D": "Z českého jazyka a anglického jazyka." },
    "correct": "C"
  },
  {
    "question": "Manželé Novákovi mají malou dceru. Od kolika let musí navštěvovat jejich dcera povinně mateřskou školu?",
    "options": { "A": "Od 3 let.", "B": "Od 4 let.", "C": "Od 5 let.", "D": "Od 6 let." },
    "correct": "C"
  },
  {
    "question": "Kolik let trvá v České republice povinná školní docházka?",
    "options": { "A": "5 let.", "B": "9 let.", "C": "12 let.", "D": "15 let." },
    "correct": "B"
  },
  {
    "question": "Kdy mají žáci základních a středních škol v České republice hlavní prázdniny?",
    "options": { "A": "V září a v říjnu.", "B": "V únoru a v březnu.", "C": "V dubnu a v květnu.", "D": "V červenci a v srpnu." },
    "correct": "D"
  },
  {
    "question": "Dcera paní Svobodové ukončila studium státní závěrečnou zkouškou a obhájila diplomovou práci. Kterou školu právě ukončila?",
    "options": { "A": "Gymnázium.", "B": "Vysokou školu.", "C": "Obchodní akademii.", "D": "Střední průmyslovou školu." },
    "correct": "B"
  },
  {
    "question": "Manželé Svobodovi mají čtyři děti. Aleně jsou 4 roky, Janovi 10 let, Ivanovi 19 let a Tereze je 21 let. Které z jejich dětí má povinnou školní docházku?",
    "options": { "A": "Jan.", "B": "Ivan.", "C": "Alena.", "D": "Tereza." },
    "correct": "A"
  },
  {
    "question": "Jana Svobodová vystudovala na lékařské fakultě tříletý obor Všeobecná sestra. Který vysokoškolský titul získala?",
    "options": { "A": "Bc.", "B": "Mgr.", "C": "MgA.", "D": "MUDr." },
    "correct": "A"
  },
  {
    "question": "Na které škole získala Ing. Petra Novotná své nejvyšší vzdělání?",
    "options": { "A": "Na střední ekonomické škole.", "B": "Na střední průmyslové škole.", "C": "Na vyšší odborné škole.", "D": "Na vysoké škole." },
    "correct": "D"
  },
  {
    "question": "Jak se jmenují střední školy, které poskytují všeobecné vzdělání?",
    "options": { "A": "Gymnázia.", "B": "Obchodní akademie.", "C": "Střední odborná učiliště.", "D": "Střední průmyslové školy." },
    "correct": "A"
  },
  {
    "question": "Petr je v 9. ročníku základní školy. Na které škole nemůže pokračovat ve studiu v dalším školním roce?",
    "options": { "A": "Na gymnáziu.", "B": "Na vysoké škole.", "C": "Na střední odborné škole.", "D": "Na středním odborném učilišti." },
    "correct": "B"
  },

  { "question": "Na kterém obrázku je česká státní vlajka?", "options": { "A": "A", "B": "B", "C": "C", "D": "D" }, "correct": "C" },
  { "question": "Který dokument České republiky popisuje základní pravidla pro rozdělení státní moci na zákonodárnou, výkonnou a soudní?", "options": { "A": "Ústava.", "B": "Vládní nařízení.", "C": "Vyhláška ministerstva vnitra.", "D": "Listina základních práv a svobod." }, "correct": "A" },
  { "question": "Která věta o politickém systému České republiky je pravdivá?", "options": { "A": "Česká republika je monarchie.", "B": "Česká republika je totalitní stát.", "C": "Česká republika je federativní stát.", "D": "Česká republika je demokratický stát." }, "correct": "D" },
  { "question": "Která instituce hlasuje o důvěře vlády?", "options": { "A": "Senát.", "B": "Ústavní soud.", "C": "Poslanecká sněmovna.", "D": "Nejvyšší kontrolní úřad." }, "correct": "C" },
  { "question": "Jakým způsobem je možné změnit Ústavu České republiky?", "options": { "A": "Občané podají petici.", "B": "Parlament schválí ústavní zákon.", "C": "Ministerstvo vnitra vydá vyhlášku.", "D": "Nejvyšší správní soud vydá rozhodnutí." }, "correct": "B" },
  { "question": "Kterou z těchto vět začíná česká státní hymna?", "options": { "A": "Nad Tatrou se blýská.", "B": "Kde domov můj, kde domov můj?", "C": "Ať mír dál zůstává s touto krajinou.", "D": "Svatý Václave, vévodo české země." }, "correct": "B" },
  { "question": "Senát Parlamentu České republiky má mnoho úkolů, projednává například návrhy zákonů. Která část Ústavy ČR popisuje tyto úkoly Senátu?", "options": { "A": "Část o moci soudní.", "B": "Část o moci výkonné.", "C": "Část o moci zákonodárné.", "D": "Část o územní samosprávě." }, "correct": "C" },
  { "question": "Které barvy jsou na české státní vlajce?", "options": { "A": "Bílá, zelená, modrá.", "B": "Bílá, červená, modrá.", "C": "Bílá, zelená, červená.", "D": "Červená, modrá, zelená." }, "correct": "B" },
  { "question": "Co nepatří mezi státní symboly České republiky?", "options": { "A": "Státní pečeť.", "B": "Státní hymna.", "C": "České korunovační klenoty.", "D": "Vlajka prezidenta republiky." }, "correct": "C" },
  { "question": "Který státní symbol České republiky je na obrázku?", "options": { "A": "Státní vlajka.", "B": "Malý státní znak.", "C": "Velký státní znak.", "D": "Vlajka prezidenta republiky." }, "correct": "B" },
  { "question": "Která z těchto osob může navrhnout v České republice zákon?", "options": { "A": "Prezident republiky.", "B": "Každý poslanec.", "C": "Ústavní soudce.", "D": "Každý občan." }, "correct": "B" },
  { "question": "Pan Svoboda se chce stát poslancem Poslanecké sněmovny ČR. Kolik let nejdéle může být poslancem v jednom volebním období?", "options": { "A": "2 roky.", "B": "4 roky.", "C": "6 roků.", "D": "8 roků." }, "correct": "B" },
  { "question": "Kdo se může stát prezidentem České republiky?", "options": { "A": "Občan České republiky, který má právo volit a který dosáhl věku 18 let.", "B": "Občan České republiky, který má právo volit a který dosáhl věku 21 let.", "C": "Občan České republiky, který má právo volit a který dosáhl věku 26 let.", "D": "Občan České republiky, který má právo volit a který dosáhl věku 40 let." }, "correct": "D" },
  { "question": "Právo veta znamená možnost vrátit zákon znovu k projednání Poslanecké sněmovně a nepodepsat jej. Kdo má při schvalování zákonů právo veta?", "options": { "A": "Prezident.", "B": "Předseda vlády.", "C": "Předseda Senátu.", "D": "Předseda Ústavního soudu." }, "correct": "A" },
  { "question": "Které komory tvoří Parlament České republiky?", "options": { "A": "Senát a vláda.", "B": "Senát a ministerstva.", "C": "Poslanecká sněmovna a vláda.", "D": "Poslanecká sněmovna a Senát." }, "correct": "D" },
  { "question": "Senát Parlamentu České republiky dal souhlas ke jmenování ústavního soudce. Kdo následně jmenuje ústavního soudce?", "options": { "A": "Prezident.", "B": "Předseda vlády.", "C": "Ministr spravedlnosti.", "D": "Předseda Poslanecké sněmovny." }, "correct": "A" },
  { "question": "Kolik volených zástupců má Senát České republiky?", "options": { "A": "27.", "B": "81.", "C": "200.", "D": "281." }, "correct": "B" },
  { "question": "Která z těchto činností je úkolem Poslanecké sněmovny Parlamentu České republiky?", "options": { "A": "Poslanecká sněmovna volí prezidenta.", "B": "Poslanecká sněmovna jmenuje soudce.", "C": "Poslanecká sněmovna uděluje státní vyznamenání.", "D": "Poslanecká sněmovna projednává a schvaluje zákony." }, "correct": "D" },
  { "question": "Nouzový stav je stav při vážných krizích, haváriích nebo epidemiích. V nouzovém stavu mohou být omezena některá lidská práva a svobody. Která instituce vyhlašuje v České republice nouzový stav?", "options": { "A": "Senát.", "B": "Vláda.", "C": "Prezident.", "D": "Poslanecká sněmovna." }, "correct": "B" },
  { "question": "Tato instituce se také někdy nazývá dolní komora Parlamentu České republiky. Volby do této instituce se konají jednou za 4 roky a volí se v nich 200 zástupců. Jak se jmenuje tato instituce?", "options": { "A": "Senát.", "B": "Ústavní soud.", "C": "Poslanecká sněmovna.", "D": "Rada České národní banky." }, "correct": "C" },
  { "question": "Pan Novotný určuje výši trestu za trestné činy. Kterou funkci vykonává?", "options": { "A": "Funkci soudce.", "B": "Funkci starosty.", "C": "Funkci ministra.", "D": "Funkci prezidenta." }, "correct": "A" },
  { "question": "Soudní moc vykonávají jménem republiky nezávislé soudy. Který právní dokument popisuje podmínky jmenování soudců v České republice?", "options": { "A": "Ústava.", "B": "Trestní řád.", "C": "Notářský řád.", "D": "Občanský soudní řád." }, "correct": "A" },
  { "question": "Který z těchto soudů rozhoduje o zrušení zákonů, které neodpovídají Ústavě České republiky?", "options": { "A": "Vrchní soud.", "B": "Ústavní soud.", "C": "Krajský soud.", "D": "Nejvyšší soud." }, "correct": "B" },
  { "question": "Která instituce má za úkol chránit bezpečnost osob a majetku a veřejný pořádek?", "options": { "A": "Policie České republiky.", "B": "Armáda České republiky.", "C": "Parlament České republiky.", "D": "Ústavní soud České republiky." }, "correct": "A" },
  { "question": "Pan Novotný pracuje jako advokát. Kterou z těchto činností může dělat?", "options": { "A": "Určovat výši trestu za trestné činy.", "B": "Poskytovat placené právní služby.", "C": "Vydávat příkaz k zatčení.", "D": "Zahajovat trestní stíhání." }, "correct": "B" },
  { "question": "Na které z těchto institucí se podává trestní oznámení?", "options": { "A": "Na policii.", "B": "Na okresním soudě.", "C": "Na ministerstvu spravedlnosti.", "D": "Na obecním nebo městském úřadě." }, "correct": "A" },
  { "question": "Co je úkolem státního zástupce?", "options": { "A": "Vymáhat peníze.", "B": "Vyhlašovat rozsudky.", "C": "Zabavovat majetek dlužníkům.", "D": "Podávat obžalobu proti obviněnému." }, "correct": "D" },
  { "question": "Co je úkolem ombudsmana?", "options": { "A": "Poskytovat placené právní služby.", "B": "Rozhodovat o vině a trestu za trestné činy.", "C": "Řešit stížnosti občanů na úřady státní správy.", "D": "Zastupovat obžalovanou osobu v soudním řízení." }, "correct": "C" },
  { "question": "Paní Svobodová se chce rozvést. Která instituce rozhodne o jejím rozvodu?", "options": { "A": "Soud.", "B": "Městský úřad.", "C": "Notářský úřad.", "D": "Státní zastupitelství." }, "correct": "A" },
  { "question": "Soud odsoudil pana Nováka k 10 letům vězení. Kterým dokumentem vyhlásil soudce vinu a trest?", "options": { "A": "Žalobou.", "B": "Zprávou.", "C": "Rozsudkem.", "D": "Oznámením." }, "correct": "C" },
  { "question": "Volby v Evropské unii se konají každých pět let na základě všeobecného hlasovacího práva. Do které instituce Evropské unie volí čeští občané své zástupce?", "options": { "A": "Do Rady Evropy.", "B": "Do Evropské komise.", "C": "Do Evropského parlamentu.", "D": "Do Evropského soudu pro lidská práva." }, "correct": "C" },
  { "question": "Jak často se konají řádné volby do obecního zastupitelstva?", "options": { "A": "Jednou za dva roky.", "B": "Jednou za tři roky.", "C": "Jednou za čtyři roky.", "D": "Jednou za pět let." }, "correct": "C" },
  { "question": "Při pravidelných volbách do Senátu se vždy volí třetina senátorů. Jak často se konají volby do Senátu?", "options": { "A": "Každý rok.", "B": "Každé 2 roky.", "C": "Každé 3 roky.", "D": "Každých 5 let." }, "correct": "B" },
  { "question": "Pan Svoboda se stal krajským zastupitelem. Krajští zastupitelé zvolili pana Svobodu nejvyšším představitelem kraje. Kterou funkci teď vykonává pan Svoboda?", "options": { "A": "Senátor.", "B": "Poslanec.", "C": "Hejtman.", "D": "Primátor." }, "correct": "C" },
  { "question": "V České republice je 27 statutárních měst včetně Prahy. Kdo je nejvyšším představitelem statutárního města?", "options": { "A": "Senátor.", "B": "Hejtman.", "C": "Poslanec.", "D": "Primátor." }, "correct": "D" },
  { "question": "Koho mohou volit občané do jeho funkce?", "options": { "A": "Ministra financí.", "B": "Soudce okresního soudu.", "C": "Senátora Parlamentu České republiky.", "D": "Člena bankovní rady České národní banky." }, "correct": "C" },
  { "question": "Občané hlasovali o tom, jestli jejich obecní úřad postaví v obci novou radnici. Jak se jmenuje toto hlasování občanů?", "options": { "A": "Obecní volby.", "B": "Místní referendum.", "C": "Dotazování občanů.", "D": "Předvolební průzkum." }, "correct": "B" },
  { "question": "Paní Svobodová kandidovala v senátních volbách a voliči ji zvolili senátorkou už v prvním kole. Kolik procent voličských hlasů získala ve svém volebním obvodě?", "options": { "A": "5 procent.", "B": "26 procent.", "C": "39 procent.", "D": "53 procent." }, "correct": "D" },
  { "question": "Za jak dlouho od poslední volby prezidenta je další řádný termín prezidentských voleb?", "options": { "A": "Za pět let.", "B": "Za šest let.", "C": "Za sedm let.", "D": "Za osm let." }, "correct": "A" },
  { "question": "Od kolika let se může občan České republiky účastnit voleb jako volič?", "options": { "A": "Od 15 let.", "B": "Od 16 let.", "C": "Od 18 let.", "D": "Od 21 let." }, "correct": "C" },
  { "question": "Která z těchto vět o státním občanství České republiky je pravdivá?", "options": { "A": "Státní občanství uděluje ministerstvo zahraničních věcí.", "B": "Státní občanství získá každý, kdo se v České republice narodí.", "C": "Žádost o udělení státního občanství České republiky se musí podat osobně.", "D": "O udělení státního občanství se musí rozhodnout do 30 dnů od podání žádosti." }, "correct": "C" },
  { "question": "Který úřad vydává občanům České republiky nový občanský průkaz?", "options": { "A": "Policie ČR.", "B": "Okresní soud.", "C": "Ministerstvo spravedlnosti.", "D": "Obecní úřad nebo úřad městské části." }, "correct": "D" },
  { "question": "Paní Nováková si pořídila psa, a proto musí splnit určité povinnosti. Co paní Nováková ale nemusí udělat?", "options": { "A": "Zajistit výcvik psa.", "B": "Zajistit čip pro psa.", "C": "Přihlásit psa na obecním úřadě.", "D": "Uhradit škodu, kterou pes způsobil." }, "correct": "A" },
  { "question": "Paní Horáková se rozhodla podat písemné oznámení na souseda, protože často ruší noční klid. Na kterém úřadě může podat paní Horáková toto oznámení o přestupku?", "options": { "A": "Na obecním úřadě.", "B": "Na Ministerstvu spravedlnosti.", "C": "Na Ministerstvu pro místní rozvoj.", "D": "Na pobočce Správy sociálního zabezpečení." }, "correct": "A" },
  { "question": "Kterou službu neposkytuje Czech POINT občanům ČR?", "options": { "A": "Výpis z rejstříku trestů.", "B": "Výpis z bankovního účtu.", "C": "Výpis z katastru nemovitostí.", "D": "Výpis z bodového hodnocení řidiče." }, "correct": "B" },
  { "question": "Pan Novotný je občanem České republiky a ztratil cestovní pas. Kde může požádat o nový pas?", "options": { "A": "Na obecním úřadu.", "B": "U okresního soudu.", "C": "Na cizinecké policii.", "D": "Na ministerstvu zahraničních věcí." }, "correct": "A" },
  { "question": "Rejstřík trestů je informační systém veřejné správy, který obsahuje údaje o odsouzení fyzických a právnických osob. Které ministerstvo spravuje rejstřík trestů?", "options": { "A": "Ministerstvo vnitra.", "B": "Ministerstvo financí.", "C": "Ministerstvo obrany.", "D": "Ministerstvo spravedlnosti." }, "correct": "D" },
  { "question": "Panu Novotnému je 35 let a platnost jeho občanského průkazu právě končí. Proto si žádá o nový průkaz. Jak dlouho bude panu Novotnému platit jeho nový občanský průkaz?", "options": { "A": "5 let.", "B": "10 let.", "C": "20 let.", "D": "35 let." }, "correct": "B" },
  { "question": "Paní Svobodová potřebuje svému zaměstnavateli dodat úředně ověřenou kopii svého maturitního vysvědčení. Na kterém místě paní Svobodové kopii maturitního vysvědčení úředně ověří?", "options": { "A": "Na okresním soudu.", "B": "Na České školní inspekci.", "C": "Na pobočkách Czech POINT.", "D": "Na každé pobočce České spořitelny." }, "correct": "C" },
  { "question": "Trestní odpovědnost mají podle zákona také mladistvé osoby. Která z těchto osob patří mezi mladistvé?", "options": { "A": "Jana, které je 10 let.", "B": "Martina, které je 14 let.", "C": "David, kterému je 17 let.", "D": "Zdeněk, kterému je 23 let." }, "correct": "C" },
  { "question": "Paní Svobodové se rozbil nový počítač. Šla jej proto reklamovat. Do kolika dnů musí prodejce vyřídit její reklamaci?", "options": { "A": "Do 7 dnů.", "B": "Do 14 dnů.", "C": "Do 30 dnů.", "D": "Do 60 dnů." }, "correct": "C" },
  { "question": "Paní Novotná si pronajala byt na dobu neurčitou. Pronajímatel chce, aby zaplatila kauci (peněžní jistotu). Jak vysoká může být kauce podle zákona?", "options": { "A": "Maximálně ve výši 1 měsíčního nájmu.", "B": "Maximálně ve výši 3 měsíčních nájmů.", "C": "Maximálně ve výši 6 měsíčních nájmů.", "D": "Maximálně ve výši 12 měsíčních nájmů." }, "correct": "B" },
  { "question": "Pan Sokol si koupil v e-shopu novou televizi. Do kolika dnů může podle zákona odstoupit od kupní smlouvy, kterou uzavřel po internetu?", "options": { "A": "Do 14 dnů.", "B": "Do 30 dnů.", "C": "Do 60 dnů.", "D": "Do 90 dnů." }, "correct": "A" },
  { "question": "Který majetek se zapisuje do katastru nemovitostí?", "options": { "A": "Pračka.", "B": "Zahrada.", "C": "Nábytek.", "D": "Motocykl." }, "correct": "B" },
  { "question": "Paní Nováková udělila panu Pokornému plnou moc, aby ji mohl zastupovat při jednání na úřadě. Jak se označuje pan Pokorný v plné moci?", "options": { "A": "Příkazce.", "B": "Poplatník.", "C": "Zmocněnec.", "D": "Opatrovník." }, "correct": "C" },
  { "question": "Pan Novák chce sepsat svou závěť formou veřejné listiny. U koho si ji může nechat sepsat?", "options": { "A": "U notáře.", "B": "U soudce.", "C": "U advokáta.", "D": "U exekutora." }, "correct": "A" },
  { "question": "Pan Novák vymáhá peněžité a nepeněžité pohledávky (dluhy) na základě soudního rozhodnutí. Které povolání vykonává pan Novák?", "options": { "A": "Povolání notáře.", "B": "Povolání soudce.", "C": "Povolání advokáta.", "D": "Povolání exekutora." }, "correct": "D" },
  { "question": "Paní Nováková koupila pozemek a chce postavit rodinný dům. Potřebuje získat stavební povolení. Který z těchto úřadů jí vydá stavební povolení?", "options": { "A": "Finanční úřad.", "B": "Stavební úřad.", "C": "Katastrální úřad.", "D": "Živnostenský úřad." }, "correct": "B" },
  { "question": "Pan Novák si půjčil lyže z půjčovny lyží. Kterou smlouvu uzavřel pan Novák s půjčovnou?", "options": { "A": "Kupní smlouvu na vybavení.", "B": "Smlouvu o úschově vybavení.", "C": "Smlouvu o přepravě vybavení.", "D": "Nájemní smlouvu na vybavení." }, "correct": "D" },
  { "question": "Pan Novák nemůže splácet úvěry bankám. Chce požádat o vyhlášení osobního bankrotu. Která instituce bude rozhodovat o vyhlášení osobního bankrotu?", "options": { "A": "Soud.", "B": "Banka.", "C": "Úřad práce.", "D": "Finanční úřad." }, "correct": "A" },
  { "question": "Kdo může v České republice uzavřít manželství?", "options": { "A": "Svobodná žena a ženatý muž.", "B": "Vdaná žena a rozvedený muž.", "C": "Svobodná žena a svobodná žena.", "D": "Svobodná žena a rozvedený muž." }, "correct": "D" },
  { "question": "Který z těchto úřadů může ukončit manželství rozvodem?", "options": { "A": "Obecní úřad.", "B": "Okresní soud.", "C": "Městská policie.", "D": "Ministerstvo vnitra." }, "correct": "B" },
  { "question": "Manželé Svobodovi jsou občané České republiky. Chtějí adoptovat dítě z dětského domova. Která instituce rozhoduje o adopci?", "options": { "A": "Soud.", "B": "Policie.", "C": "Obecní úřad.", "D": "Ministerstvo vnitra." }, "correct": "A" },
  { "question": "Který z těchto dokumentů vydává matriční úřad?", "options": { "A": "Oddací list.", "B": "Zbrojní pas.", "C": "Řidičský průkaz.", "D": "Průkaz pojištěnce." }, "correct": "A" },
  { "question": "Která informace není uvedena v úmrtním listě?", "options": { "A": "Příčina smrti.", "B": "Datum a místo úmrtí.", "C": "Datum narození zemřelé osoby.", "D": "Celé jméno a příjmení zemřelé osoby." }, "correct": "A" },
  { "question": "Paní Horáková ztratila rodný list. Kde musí požádat o vydání nového rodného listu?", "options": { "A": "Na policii.", "B": "Na matričním úřadě.", "C": "Na ministerstvu vnitra.", "D": "Na správě sociálního zabezpečení." }, "correct": "B" },
  { "question": "Paní Nováková změnila po rozvodu příjmení. U které z těchto institucí změnu příjmení oznámila?", "options": { "A": "U soudu.", "B": "Na policii.", "C": "Na matričním úřadě.", "D": "Na Českém statistickém úřadě." }, "correct": "C" },
  { "question": "Jak se jmenuje dokument, který manželům vydá matriční úřad po uzavření manželství?", "options": { "A": "Rodný list.", "B": "Oddací list.", "C": "Prohlášení o uzavření manželství.", "D": "Doklad o registrovaném partnerství." }, "correct": "B" },
  { "question": "Který matriční doklad získá český občan po narození?", "options": { "A": "Rodný list.", "B": "Oddací list.", "C": "Cestovní pas.", "D": "Občanský průkaz." }, "correct": "A" },
  { "question": "Manželé Novákovi se rozvedli. Jak se jmenuje dokument, který dostanou po rozvodu?", "options": { "A": "Žaloba.", "B": "Rodný list.", "C": "Rozhodnutí.", "D": "Rozsudek soudu." }, "correct": "D" },
  { "question": "Která instituce vydává v České republice bankovky a mince?", "options": { "A": "Česká hospodářská komora.", "B": "Český statistický úřad.", "C": "Česká národní banka.", "D": "Ministerstvo financí." }, "correct": "C" },
  { "question": "Na bankovce je známá česká spisovatelka – autorka knihy Babička. Jak se tato žena jmenuje?", "options": { "A": "Svatá Ludmila.", "B": "Ema Destinnová.", "C": "Božena Němcová.", "D": "Anežka Přemyslovna." }, "correct": "C" },
  { "question": "Jak se nazývá měna České republiky?", "options": { "A": "Euro.", "B": "Haléř.", "C": "Koruna česká.", "D": "Československá koruna." }, "correct": "C" },
  { "question": "Na české stokorunové bankovce je slavný český král a římský císař. Jak se tento muž jmenuje?", "options": { "A": "Karel IV.", "B": "Rudolf II.", "C": "František Josef I.", "D": "Přemysl Otakar II." }, "correct": "A" },
  { "question": "Jakou nejvyšší hodnotu má platná česká bankovka?", "options": { "A": "500 korun českých.", "B": "1 000 korun českých.", "C": "2 000 korun českých.", "D": "5 000 korun českých." }, "correct": "D" },
  { "question": "Jakou nejnižší hodnotu má platná česká bankovka?", "options": { "A": "50 korun českých.", "B": "100 korun českých.", "C": "200 korun českých.", "D": "500 korun českých." }, "correct": "B" },
  { "question": "Paní Svobodová si kupuje nové auto za 650 000 korun. Chce zaplatit v hotovosti, ale prodejce nemůže podle zákona tak velkou peněžní částku přijmout. Jakou maximální částku v hotovosti může prodejce přijmout?", "options": { "A": "100 000 Kč.", "B": "270 000 Kč.", "C": "400 000 Kč.", "D": "470 000 Kč." }, "correct": "B" },
  { "question": "Česká národní banka (ČNB) je centrální banka v ČR, která vykonává dohled nad finančním trhem v zemi. Kdo je nejvyšší představitel České národní banky?", "options": { "A": "Prezident.", "B": "Guvernér.", "C": "Předseda.", "D": "Ředitel." }, "correct": "B" },
  { "question": "Základní úroková sazba ovlivňuje např. komerční hypoteční úrok nebo úroky k půjčkám. Která instituce stanovuje základní úrokovou sazbu v České republice?", "options": { "A": "Vláda.", "B": "Finanční úřad.", "C": "Ministerstvo financí.", "D": "Česká národní banka." }, "correct": "D" },
  { "question": "Jakou nejvyšší hodnotu má platná česká mince?", "options": { "A": "10 korun českých.", "B": "20 korun českých.", "C": "50 korun českých.", "D": "100 korun českých." }, "correct": "C" },
  { "question": "Pan Novotný je podnikatel a má ze zákona povinnost platit daně. Který úřad kontroluje, jak platí daně?", "options": { "A": "Obecní úřad.", "B": "Finanční úřad.", "C": "Katastrální úřad.", "D": "Živnostenský úřad." }, "correct": "B" },
  { "question": "Celní správa České republiky vybírá cla a spotřební daně a má různé úkoly při ochraně ekonomických zájmů ČR. Pod které ministerstvo Celní správa ČR patří?", "options": { "A": "Ministerstvo vnitra.", "B": "Ministerstvo financí.", "C": "Ministerstvo spravedlnosti.", "D": "Ministerstvo pro místní rozvoj." }, "correct": "B" },
  { "question": "Nepřímé daně jsou součástí ceny výrobků a služeb. Která z těchto daní je nepřímá?", "options": { "A": "Silniční daň.", "B": "Spotřební daň.", "C": "Daň z příjmů fyzických osob.", "D": "Daň z příjmů právnických osob." }, "correct": "B" },
  { "question": "Paní Svobodová si koupila domů novou televizi. Kterou daň musí zaplatit v ceně televize?", "options": { "A": "Daň z nemovitých věcí.", "B": "Daň z přidané hodnoty.", "C": "Spotřební daň.", "D": "Daň z příjmů." }, "correct": "B" },
  { "question": "Na kterém úřadu podává podnikatel daňové přiznání?", "options": { "A": "Na obecním úřadu.", "B": "Na finančním úřadu.", "C": "Na ministerstvu financí.", "D": "Na finančním ředitelství." }, "correct": "B" },
  { "question": "Ze kterého z těchto druhů příjmů zaplatí paní Svobodová daň?", "options": { "A": "Z nemocenské.", "B": "Z pronájmu bytu.", "C": "Ze sociálních dávek.", "D": "Z podpory v nezaměstnanosti." }, "correct": "B" },
  { "question": "V současnosti jsou v České republice dvě sazby daně z přidané hodnoty (DPH). Jaká je jejich procentuální výše?", "options": { "A": "10 % a 5 %.", "B": "15 % a 10 %.", "C": "21 % a 12 %.", "D": "26 % a 16 %." }, "correct": "C" },
  { "question": "Co označuje zkratka DPH?", "options": { "A": "Daň z příjmů.", "B": "Hrubý domácí produkt.", "C": "Daň z přidané hodnoty.", "D": "Dohodu o provedení práce." }, "correct": "C" },
  { "question": "Který druh zboží má v ceně spotřební daň?", "options": { "A": "Tvrdý alkohol.", "B": "Elektrická energie.", "C": "Sportovní oblečení.", "D": "Elektronická zařízení." }, "correct": "A" },
  { "question": "Pan Svoboda má zaplatit dluh 2 500 Kč na dani z příjmů. Kterému úřadu dluh zaplatí?", "options": { "A": "Úřadu práce.", "B": "Celnímu úřadu.", "C": "Finančnímu úřadu.", "D": "Českému statistickému úřadu." }, "correct": "C" },

     { "question": "Který úřad poskytuje podporu v nezaměstnanosti?", "options": { "A": "Živnostenský úřad.", "B": "Finanční úřad.", "C": "Krajský úřad.", "D": "Úřad práce." }, "correct": "D" },
  { "question": "Paní Svobodová má nárok na starobní důchod. Která instituce v České republice vydá rozhodnutí o výši jejího důchodu?", "options": { "A": "Úřad práce.", "B": "Ministerstvo vnitra.", "C": "Ministerstvo zdravotnictví.", "D": "Česká správa sociálního zabezpečení." }, "correct": "D" },
  { "question": "Který druh finanční pomoci nevyplácí Česká správa sociálního zabezpečení?", "options": { "A": "Mateřskou.", "B": "Nemocenskou.", "C": "Starobní důchod.", "D": "Podporu v nezaměstnanosti." }, "correct": "D" },
  { "question": "Pan Novák pracuje ve stavební firmě, ale v současné době je nemocný. Nedostává mzdu, ale peněžitou dávku. Jak se tato dávka jmenuje?", "options": { "A": "Výživné.", "B": "Ošetřovné.", "C": "Nemocenská.", "D": "Podpora v nezaměstnanosti." }, "correct": "C" },
  { "question": "Paní Novotná pečuje o svou maminku, která je vážně nemocná a není schopná se sama o sebe postarat. O kterou sociální dávku je možné v této situaci požádat?", "options": { "A": "O náhradní výživné.", "B": "O příspěvek na péči.", "C": "O rodičovský příspěvek.", "D": "O mimořádnou okamžitou pomoc." }, "correct": "B" },
  { "question": "Který úřad rozhoduje o přiznání dávek v hmotné nouzi?", "options": { "A": "Úřad práce.", "B": "Ministerstvo financí.", "C": "Charita České republiky.", "D": "Česká správa sociálního zabezpečení." }, "correct": "A" },
  { "question": "Panu Novákovi je 60 let a je nezaměstnaný. Jaká je nejdelší doba, po kterou může dostávat podporu v nezaměstnanosti?", "options": { "A": "6 měsíců.", "B": "11 měsíců.", "C": "18 měsíců.", "D": "24 měsíců." }, "correct": "B" },
  { "question": "Paní Nováková pracuje jako učitelka na základní škole a čeká své první dítě. Má 3 týdny před porodem. Kterou z těchto peněžitých dávek může dostat před narozením dítěte?", "options": { "A": "Porodné.", "B": "Ošetřovné.", "C": "Mateřskou.", "D": "Rodičovskou." }, "correct": "C" },
  { "question": "Manželům Novotným se narodilo dítě. Na jak dlouho si podle zákona může vzít pan Novotný otcovskou dovolenou?", "options": { "A": "Na 5 dní.", "B": "Na 14 dní.", "C": "Na 31 dní.", "D": "Na 60 dní." }, "correct": "B" },
  { "question": "Paní Svobodová ztratila práci. Chce se proto při osobní návštěvě zapsat do evidence úřadu práce. Který doklad nemusí předložit k žádosti o zprostředkování zaměstnání?", "options": { "A": "Rodný list.", "B": "Občanský průkaz.", "C": "Zápočtový list od bývalého zaměstnavatele.", "D": "Potvrzení o ukončení pracovněprávního vztahu." }, "correct": "A" },
  { "question": "Paní Novotná dává výpověď ze svého pracovního poměru. Jaká je délka výpovědní doby podle zákona?", "options": { "A": "Nejvíce 3 dny.", "B": "Nejvíce 15 dnů.", "C": "Nejméně 1 měsíc.", "D": "Nejméně 2 měsíce." }, "correct": "D" },
  { "question": "Výpovědní doba se počítá ode dne doručení výpovědi. Jak dlouhá je výpovědní doba u dohody o pracovní činnosti (DPČ)?", "options": { "A": "15 dní.", "B": "30 dní.", "C": "60 dní.", "D": "90 dní." }, "correct": "A" },
  { "question": "Který z těchto údajů musí být podle zákona v každém případě v pracovní smlouvě?", "options": { "A": "Pracovní doba.", "B": "Počet dnů dovolené.", "C": "Místo výkonu práce.", "D": "Termín výplaty mzdy." }, "correct": "C" },
  { "question": "Paní Svobodová pracuje od 1. ledna jako zahradnice. S majitelem zahradnictví podepsala dohodu o provedení práce (DPP). Kolik hodin může odpracovat v tomto zahradnictví v jednom kalendářním roce?", "options": { "A": "Maximálně 150 hodin.", "B": "Maximálně 200 hodin.", "C": "Maximálně 250 hodin.", "D": "Maximálně 300 hodin." }, "correct": "D" },
  { "question": "Pan Novák má zaměstnání na plný pracovní úvazek. Kolik hodin týdně musí podle zákona pracovat?", "options": { "A": "35 hodin.", "B": "40 hodin.", "C": "45 hodin.", "D": "50 hodin." }, "correct": "B" },
  { "question": "Který zákon nebo zákoník upravuje vztah mezi zaměstnavatelem a zaměstnancem?", "options": { "A": "Živnostenský zákon.", "B": "Trestní zákoník.", "C": "Zákon o rodině.", "D": "Zákoník práce." }, "correct": "D" },
  { "question": "Pan Novák uzavřel s firmou Stavby, s. r. o., pracovní poměr na dobu určitou. Jakou nejdelší dobu může trvat tento nový pracovní poměr bez prodloužení?", "options": { "A": "Jeden rok.", "B": "Dva roky.", "C": "Tři roky.", "D": "Čtyři roky." }, "correct": "C" },
  { "question": "Paní Nováková má nové zaměstnání. Bude pracovat jako prodavačka. Získala pracovní smlouvu na dobu neurčitou s maximální zkušební dobou. Jaká bude podle zákona délka zkušební doby paní Novákové?", "options": { "A": "4 měsíce.", "B": "6 měsíců.", "C": "9 měsíců.", "D": "12 měsíců." }, "correct": "A" },
  { "question": "Co musí obsahovat platná výpověď z pracovního poměru, kterou podává zaměstnanec?", "options": { "A": "Podpis zaměstnance.", "B": "Rodné číslo zaměstnance.", "C": "Číslo bankovního účtu zaměstnance.", "D": "Číslo občanského průkazu zaměstnance." }, "correct": "A" },
  { "question": "Paní Novákové je 45 let a pracuje jako recepční v hotelu na směny. Kolik hodin nesmí přesáhnout jedna směna?", "options": { "A": "6 hodin.", "B": "8 hodin.", "C": "10 hodin.", "D": "12 hodin." }, "correct": "D" },
  { "question": "Pan Novák je osoba samostatně výdělečně činná (OSVČ). Jak se nazývají jeho příjmy?", "options": { "A": "Příjmy z důchodového připojištění.", "B": "Příjmy ze samostatné činnosti.", "C": "Příjmy ze závislé činnosti.", "D": "Příjmy z pronájmu bytu." }, "correct": "B" },
  { "question": "Která práce není živnost?", "options": { "A": "Policejní služba.", "B": "Kadeřnické služby.", "C": "Průvodcovské služby.", "D": "Služby soukromého detektiva." }, "correct": "A" },
  { "question": "Podnikatel založil firmu. Ke které z uvedených daní se musel zaregistrovat na finančním úřadě?", "options": { "A": "K dani z příjmů.", "B": "K dani spotřební.", "C": "K dani z nemovitosti.", "D": "K dani z přidané hodnoty." }, "correct": "A" },
  { "question": "Které pojištění musí zaměstnavatel v České republice platit za své zaměstnance?", "options": { "A": "Životní pojištění.", "B": "Havarijní pojištění.", "C": "Zdravotní pojištění.", "D": "Důchodové připojištění." }, "correct": "C" },
  { "question": "Pan Novák je majitelem obchodu s oděvy. Který úřad vydal panu Novákovi povolení k podnikání?", "options": { "A": "Okresní soud.", "B": "Finanční úřad.", "C": "Živnostenský úřad.", "D": "Ministerstvo práce a sociálních věcí." }, "correct": "C" },
  { "question": "Které informace obsahuje obchodní rejstřík?", "options": { "A": "Informace o dluzích firmy.", "B": "Informace o identifikačním čísle firmy.", "C": "Informace o obchodních partnerech firmy.", "D": "Informace o ročním obchodním obratu firmy." }, "correct": "B" },
  { "question": "V obchodním rejstříku jsou informace o podnikatelích na území České republiky a je přístupný veřejnosti v online podobě. Která instituce zveřejňuje obchodní rejstřík v České republice?", "options": { "A": "Ministerstvo vnitra ČR.", "B": "Ministerstvo financí ČR.", "C": "Ministerstvo spravedlnosti ČR.", "D": "Ministerstvo průmyslu a obchodu ČR." }, "correct": "C" },
  { "question": "Co nepatří mezi činnosti živnostenského úřadu?", "options": { "A": "Přijímat ohlášení živností.", "B": "Přijímat žádosti o koncesi.", "C": "Přijímat daňová přiznání podnikatelů.", "D": "Vydávat výpisy z živnostenského rejstříku." }, "correct": "C" },
  { "question": "Pan Horák je truhlář a podniká jako osoba samostatně výdělečně činná (OSVČ). Které z těchto pojištění si musí pan Horák platit?", "options": { "A": "Pojištění majetku.", "B": "Zdravotní pojištění.", "C": "Nemocenské pojištění.", "D": "Pojištění odpovědnosti podnikatelů." }, "correct": "B" },
  { "question": "Který z těchto dokumentů potřebuje občan k vykonávání volné živnosti?", "options": { "A": "Rodný list.", "B": "Výuční list.", "C": "Daňové přiznání.", "D": "Výpis ze živnostenského rejstříku." }, "correct": "D" },
  { "question": "Jaké je mezinárodní postavení České republiky?", "options": { "A": "Je závislým územím Evropské unie.", "B": "Je součástí státu Rakousko-Uhersko.", "C": "Je jednou z částí federace Evropská unie.", "D": "Je nezávislou republikou a je členem Evropské unie." }, "correct": "D" },
  { "question": "Česko se nachází v hlavním evropském rozvodí. Odtéká z něj voda řekami do tří moří. Do kterého moře se vlévá řeka Labe?", "options": { "A": "Do Černého moře.", "B": "Do Severního moře.", "C": "Do Baltského moře.", "D": "Do Jaderského moře." }, "correct": "B" },
  { "question": "Kde pramení řeka Labe?", "options": { "A": "V Orlických horách.", "B": "V Krušných horách.", "C": "V Krkonoších.", "D": "Na Šumavě." }, "correct": "C" },
  { "question": "Praha je hlavním městem České republiky. Které číslo na mapě označuje Prahu?", "options": { "A": "1.", "B": "2.", "C": "3.", "D": "4." }, "correct": "D" },
  { "question": "Jaká je přibližně rozloha Česka?", "options": { "A": "39 000 km2.", "B": "79 000 km2.", "C": "119 000 km2.", "D": "159 000 km2." }, "correct": "B" },
  { "question": "Která dvojice krajů se nachází ve východních Čechách?", "options": { "A": "Liberecký kraj a Ústecký kraj.", "B": "Ústecký kraj a Karlovarský kraj.", "C": "Plzeňský kraj a Karlovarský kraj.", "D": "Královéhradecký kraj a Pardubický kraj." }, "correct": "D" },
  { "question": "Ve kterém klimatickém pásu se nachází Česká republika?", "options": { "A": "V mírném.", "B": "V polárním.", "C": "V tropickém.", "D": "V subtropickém." }, "correct": "A" },
  { "question": "Nejvyšší hora Moravy se nachází v pohoří Hrubý Jeseník. Jak se tato hora jmenuje?", "options": { "A": "Plechý.", "B": "Praděd.", "C": "Sněžka.", "D": "Klínovec." }, "correct": "B" },
  { "question": "Které státy sousedí s Českem?", "options": { "A": "Maďarsko, Německo, Rakousko, Ukrajina.", "B": "Maďarsko, Polsko, Rakousko, Slovensko.", "C": "Německo, Polsko, Rakousko, Slovensko.", "D": "Německo, Polsko, Ukrajina, Slovensko." }, "correct": "C" },
  { "question": "Nejvyšší hora v České republice je Sněžka. Jakou má přibližně nadmořskou výšku?", "options": { "A": "800 metrů nad mořem.", "B": "1 600 metrů nad mořem.", "C": "2 400 metrů nad mořem.", "D": "3 200 metrů nad mořem." }, "correct": "B" },
  { "question": "Kladruby nad Labem a okolní krajina byly v roce 2019 zapsány na seznam světového dědictví UNESCO. Čím je tato obec a její okolí známá?", "options": { "A": "Chovem koní.", "B": "Těžbou stříbra.", "C": "Bukovými lesy.", "D": "Termálními prameny." }, "correct": "A" },
  { "question": "Který národní park leží na Moravě?", "options": { "A": "Národní park Podyjí.", "B": "Národní park Šumava.", "C": "Krkonošský národní park.", "D": "Národní park České Švýcarsko." }, "correct": "A" },
  { "question": "V Česku se nachází několik významných center zimních sportů. Které z těchto míst je známé jako centrum zimních sportů?", "options": { "A": "Most.", "B": "Třeboň.", "C": "Poděbrady.", "D": "Špindlerův Mlýn." }, "correct": "D" },
  { "question": "Jizerskohorské bučiny jsou od roku 2021 na seznamu světového dědictví UNESCO. Které číslo na mapě označuje tuto přírodní památku?", "options": { "A": "1.", "B": "2.", "C": "3.", "D": "4." }, "correct": "C" },
  { "question": "Orlík je přehrada, která zadržuje v Česku nejvíce vody. Jak se jmenuje řeka, na které se přehrada Orlík nachází?", "options": { "A": "Labe.", "B": "Vltava.", "C": "Sázava.", "D": "Morava." }, "correct": "B" },
  { "question": "Památná hora Čechů se nachází v Ústeckém kraji blízko Roudnice nad Labem. Jak se tato hora jmenuje?", "options": { "A": "Medvědín.", "B": "Klínovec.", "C": "Praděd.", "D": "Říp." }, "correct": "D" },
  { "question": "V roce 2019 byla na seznam památek UNESCO zapsána hornická kulturní krajina Krušnohoří. Které číslo na mapě označuje tento region?", "options": { "A": "1.", "B": "2.", "C": "3.", "D": "4." }, "correct": "B" },
  { "question": "Které město zapsané na seznamu UNESCO leží v jižních Čechách?", "options": { "A": "Třebíč.", "B": "Kroměříž.", "C": "Kutná Hora.", "D": "Český Krumlov." }, "correct": "D" },
  { "question": "Jak se jmenuje nejvyšší pohoří na Moravě?", "options": { "A": "Krušné hory.", "B": "Krkonoše.", "C": "Jeseníky.", "D": "Šumava." }, "correct": "C" },
  { "question": "Město Žatec a okolní krajina byly v roce 2023 zapsány na seznam UNESCO. Čím je toto město a jeho okolí známé?", "options": { "A": "Pěstuje se tam vinná réva.", "B": "Pěstuje se tam chmel.", "C": "Chovají se tam kapři.", "D": "Chovají se tam koně." }, "correct": "B" },
  { "question": "Ve kterém městě sídlí Západočeská univerzita (ZČU)?", "options": { "A": "V Plzni.", "B": "V Ústí nad Labem.", "C": "V Karlových Varech.", "D": "V Českých Budějovicích." }, "correct": "A" },
  { "question": "Jak se jmenuje největší letiště v České republice?", "options": { "A": "Praha-Kbely.", "B": "Brno-Tuřany.", "C": "Letiště Karlovy Vary.", "D": "Letiště Václava Havla Praha." }, "correct": "D" },
  { "question": "Kateřinu přijali ke studiu na Univerzitě Palackého, která je nejstarší univerzitou na Moravě. Ve městě, kde bude studovat, je také památka UNESCO – sloup Nejsvětější Trojice. Ve kterém městě bude Kateřina studovat?", "options": { "A": "Ve Zlíně.", "B": "V Jihlavě.", "C": "V Olomouci.", "D": "V Pardubicích." }, "correct": "C" },
  { "question": "Kladno, Příbram a Mladá Boleslav jsou města, která se nacházejí v největším kraji České republiky. Ve kterém kraji se tato města nacházejí?", "options": { "A": "V Ústeckém kraji.", "B": "Ve Zlínském kraji.", "C": "Ve Středočeském kraji.", "D": "V Jihomoravském kraji." }, "correct": "C" },
  { "question": "Které město je centrem Moravskoslezského kraje?", "options": { "A": "Třebíč.", "B": "Jihlava.", "C": "Ostrava.", "D": "Pardubice." }, "correct": "C" },
  { "question": "Ve kterém kraji České republiky se nacházejí města Jindřichův Hradec, Tábor a Písek?", "options": { "A": "Ve Zlínském kraji.", "B": "V Jihočeském kraji.", "C": "Ve Středočeském kraji.", "D": "V Moravskoslezském kraji." }, "correct": "B" },
  { "question": "Perník je tradiční české pečivo s medem a kořením. Které město je slavné díky výrobě perníku?", "options": { "A": "Hořice.", "B": "Pardubice.", "C": "Karlovy Vary.", "D": "Mariánské Lázně." }, "correct": "B" },
  { "question": "Univerzita Tomáše Bati se jmenuje po významném podnikateli a zakladateli obuvnické firmy. Ve kterém krajském městě tato univerzita sídlí?", "options": { "A": "V Brně.", "B": "Ve Zlíně.", "C": "V Ostravě.", "D": "V Pardubicích." }, "correct": "B" },
  { "question": "Jihlava je krajské město a leží blízko dálnice D1. Ve kterém kraji je město Jihlava?", "options": { "A": "V Kraji Vysočina.", "B": "V Pardubickém kraji.", "C": "Ve Středočeském kraji.", "D": "V Moravskoslezském kraji." }, "correct": "A" },
  { "question": "Pan Novák jede autem na služební cestu z Prahy do Děčína. Použije dálnici D8. Kolem kterého krajského města musí do Děčína projet?", "options": { "A": "Kolem Brna.", "B": "Kolem Pardubic.", "C": "Kolem Ústí nad Labem.", "D": "Kolem Českých Budějovic." }, "correct": "C" },

{ "category": "OCHRANA ŽIVOTNÍHO PROSTŘEDÍ", "question": "Česko má bohaté zásoby podzemních minerálních vod. Pramen minerální vody Vincentka se nachází v lázních Luhačovice. Které číslo na mapě označuje město Luhačovice?", "options": { "A": "1.", "B": "2.", "C": "3.", "D": "4." }, "correct": "C" },
  { "category": "OCHRANA ŽIVOTNÍHO PROSTŘEDÍ", "question": "Který národní park leží u hranice Česka s Polskem?", "options": { "A": "Národní park Podyjí.", "B": "Šumavský národní park.", "C": "Krkonošský národní park.", "D": "Národní park České Švýcarsko." }, "correct": "C" },
  { "category": "OCHRANA ŽIVOTNÍHO PROSTŘEDÍ", "question": "Třídění odpadu pomáhá chránit životní prostředí. Kterou barvu má kontejner na papír?", "options": { "A": "Bílou.", "B": "Žlutou.", "C": "Modrou.", "D": "Zelenou." }, "correct": "C" },
  { "category": "OCHRANA ŽIVOTNÍHO PROSTŘEDÍ", "question": "Černé a Čertovo jezero jsou největšími přírodními jezery v České republice. Nacházejí se na Šumavě. Které číslo na mapě označuje tuto oblast?", "options": { "A": "1.", "B": "2.", "C": "3.", "D": "4." }, "correct": "C" },
  { "category": "OCHRANA ŽIVOTNÍHO PROSTŘEDÍ", "question": "Tříděný odpad se ukládá do barevných kontejnerů. Co nepatří do žlutého kontejneru?", "options": { "A": "Igelitové tašky.", "B": "Plastové nádobí.", "C": "PET láhve od nápojů.", "D": "Skleněné láhve od nápojů." }, "correct": "D" },
  { "category": "OCHRANA ŽIVOTNÍHO PROSTŘEDÍ", "question": "Pan Svoboda třídí odpad. Co dává do modrého kontejneru?", "options": { "A": "Sklo.", "B": "Papír.", "C": "Plasty.", "D": "Bioodpad." }, "correct": "B" },
  { "category": "OCHRANA ŽIVOTNÍHO PROSTŘEDÍ", "question": "Tříděný odpad se ukládá do barevných kontejnerů. Co patří do hnědého kontejneru?", "options": { "A": "Plechovky a drobný kovový odpad.", "B": "Časopisy, noviny, sešity a papírové obaly.", "C": "Zbytky ovoce a zeleniny, odpad rostlinného původu.", "D": "Nefunkční elektrické spotřebiče, baterie a akumulátory." }, "correct": "C" },
  { "category": "OCHRANA ŽIVOTNÍHO PROSTŘEDÍ", "question": "Jeden ze čtyř národních parků Česka je známý skálami a Pravčickou bránou. Který národní park to je?", "options": { "A": "Národní park Podyjí.", "B": "Národní park Šumava.", "C": "Krkonošský národní park.", "D": "Národní park České Švýcarsko." }, "correct": "D" },
  { "category": "OCHRANA ŽIVOTNÍHO PROSTŘEDÍ", "question": "Tříděný odpad se ukládá do barevných kontejnerů. Co patří do zeleného kontejneru?", "options": { "A": "Skleněné láhve.", "B": "Noviny a časopisy.", "C": "PET láhve od nápojů.", "D": "Použité elektrické přístroje." }, "correct": "A" },
  { "category": "OCHRANA ŽIVOTNÍHO PROSTŘEDÍ", "question": "V Česku se nacházejí čtyři území s nejvyšším stupněm ochrany přírody. Jak se tato území nazývají?", "options": { "A": "Národní parky.", "B": "Přírodní rezervace.", "C": "Chráněné krajinné oblasti.", "D": "Ochranná pásma vodního zdroje." }, "correct": "A" },
  { "category": "SOCIOKULTURNÍ SOUVISLOSTI", "question": "Kolik obyvatel má přibližně Česká republika?", "options": { "A": "5,9 milionu.", "B": "10,9 milionu.", "C": "15,9 milionu.", "D": "20,9 milionu." }, "correct": "B" },
  { "category": "SOCIOKULTURNÍ SOUVISLOSTI", "question": "Národnostní menšinou je skupina občanů České republiky, kteří se hlásí k jiné než české národnosti. Kdo tvoří největší národnostní menšinu v Česku?", "options": { "A": "Poláci.", "B": "Němci.", "C": "Slováci.", "D": "Vietnamci." }, "correct": "C" },
  { "category": "SOCIOKULTURNÍ SOUVISLOSTI", "question": "Kulturní region Haná je významnou zemědělskou oblastí a je známý lidovými zvyky. Které krajské město je centrem kulturního regionu Haná?", "options": { "A": "Ostrava.", "B": "Olomouc.", "C": "Hradec Králové.", "D": "České Budějovice." }, "correct": "B" },
  { "category": "SOCIOKULTURNÍ SOUVISLOSTI", "question": "Která televize má podle zákona za úkol produkovat a vysílat vzdělávací programy a programy pro děti?", "options": { "A": "Česká televize.", "B": "Televize Nova.", "C": "Televize Prima.", "D": "Televize Barrandov." }, "correct": "A" },
  { "category": "SOCIOKULTURNÍ SOUVISLOSTI", "question": "Kolik obyvatel má hlavní město Praha?", "options": { "A": "Přibližně 500 000.", "B": "Přibližně 1 400 000.", "C": "Přibližně 6 500 000.", "D": "Přibližně 10 900 000." }, "correct": "B" },
  { "category": "SOCIOKULTURNÍ SOUVISLOSTI", "question": "Toto město bylo a je historickým centrem českého Slezska. Nachází se zde Slezská univerzita, Slezské zemské muzeum i Slezské divadlo. Jak se město jmenuje?", "options": { "A": "Brno.", "B": "Opava.", "C": "Jihlava.", "D": "Kroměříž." }, "correct": "B" },
  { "category": "SOCIOKULTURNÍ SOUVISLOSTI", "question": "Které náboženství je v Česku nejrozšířenější?", "options": { "A": "Islám.", "B": "Judaismus.", "C": "Křesťanství.", "D": "Buddhismus." }, "correct": "C" },
  { "category": "SOCIOKULTURNÍ SOUVISLOSTI", "question": "Město Plzeň je čtvrtým největším městem České republiky a důležitým ekonomickým centrem. Které číslo na mapě označuje město Plzeň?", "options": { "A": "1.", "B": "2.", "C": "3.", "D": "4." }, "correct": "B" },
  { "category": "SOCIOKULTURNÍ SOUVISLOSTI", "question": "Které tvrzení odpovídá postavení žen v české společnosti?", "options": { "A": "Ženy nepracují v justici.", "B": "Ženy nepracují v armádě.", "C": "Ženy mají stejná práva jako muži.", "D": "Ženy mají omezené volební právo." }, "correct": "C" },
  { "category": "SOCIOKULTURNÍ SOUVISLOSTI", "question": "Brno je největším městem Moravy a také druhým největším městem České republiky. Kolik obyvatel přibližně žije v Brně?", "options": { "A": "100 000.", "B": "400 000.", "C": "720 000.", "D": "1 360 000." }, "correct": "B" },
  { "category": "SOCIOEKONOMICKÉ SOUVISLOSTI", "question": "Ve kterém kraji je atomová elektrárna Temelín?", "options": { "A": "V Ústeckém kraji.", "B": "V Jihočeském kraji.", "C": "V Jihomoravském kraji.", "D": "V Moravskoslezském kraji." }, "correct": "B" },
  { "category": "SOCIOEKONOMICKÉ SOUVISLOSTI", "question": "Která z těchto měst spojuje dálnice D1?", "options": { "A": "Prahu a Pardubice.", "B": "Prahu a Liberec.", "C": "Prahu a Plzeň.", "D": "Prahu a Brno." }, "correct": "D" },
  { "category": "SOCIOEKONOMICKÉ SOUVISLOSTI", "question": "Jak se jmenuje slavný český podnik, který vyrábí klavíry?", "options": { "A": "Amati.", "B": "Petrof.", "C": "Moser.", "D": "Koh-i-noor." }, "correct": "B" },
  { "category": "SOCIOEKONOMICKÉ SOUVISLOSTI", "question": "V Kopřivnici se vyrábí nákladní automobily tradiční značky. Jak se tato značka jmenuje?", "options": { "A": "Tatra.", "B": "Zetor.", "C": "Škoda.", "D": "Karosa." }, "correct": "A" },
  { "category": "SOCIOEKONOMICKÉ SOUVISLOSTI", "question": "Který pivovar vyrábí pivo značky Pilsner Urquell?", "options": { "A": "Starobrno.", "B": "Staropramen.", "C": "Plzeňský Prazdroj.", "D": "Budějovický Budvar." }, "correct": "C" },
  { "category": "SOCIOEKONOMICKÉ SOUVISLOSTI", "question": "Značka Kofola patří od 60. let 20. století mezi tradiční české značky. Které výrobky mají označení Kofola?", "options": { "A": "Mléčné výrobky.", "B": "Sportovní oblečení.", "C": "Alkoholické nápoje.", "D": "Nealkoholické nápoje." }, "correct": "D" },
  { "category": "SOCIOEKONOMICKÉ SOUVISLOSTI", "question": "Z Prahy do Ostravy vede nejdůležitější železniční trať v Česku. Kterým z těchto měst tato železniční trať prochází?", "options": { "A": "Brno.", "B": "Jihlava.", "C": "Liberec.", "D": "Olomouc." }, "correct": "D" },
  { "category": "SOCIOEKONOMICKÉ SOUVISLOSTI", "question": "Ve kterém městě se vyrábí pivo značky Budvar?", "options": { "A": "V Plzni", "B": "V Praze.", "C": "Ve Velkých Popovicích.", "D": "V Českých Budějovicích." }, "correct": "D" },
  { "category": "SOCIOEKONOMICKÉ SOUVISLOSTI", "question": "Která značka osobních automobilů se vyrábí ve městě Mladá Boleslav?", "options": { "A": "Hyundai.", "B": "Peugeot.", "C": "Škoda.", "D": "Tatra." }, "correct": "C" },
  { "category": "SOCIOEKONOMICKÉ SOUVISLOSTI", "question": "Tradiční českou značkou je Becherovka. Ve kterém městě se tento alkoholický nápoj vyrábí?", "options": { "A": "V Plzni.", "B": "V Praze.", "C": "V Karlových Varech.", "D": "V Českých Budějovicích." }, "correct": "C" },
  { "category": "MEZINÁRODNÍ SOUVISLOSTI", "question": "Jak se jmenuje mezinárodní vojenská organizace, která zajišťuje bezpečnost České republiky?", "options": { "A": "NATO.", "B": "CEFTA.", "C": "Evropská unie.", "D": "Varšavská smlouva." }, "correct": "A" },
  { "category": "MEZINÁRODNÍ SOUVISLOSTI", "question": "Česká republika je členem Evropské unie. Které z těchto měst je sídlem hlavních orgánů Evropské unie?", "options": { "A": "Řím.", "B": "Paříž.", "C": "Brusel.", "D": "Londýn." }, "correct": "C" },
  { "category": "MEZINÁRODNÍ SOUVISLOSTI", "question": "V roce 2004 vstoupily do Evropské unie státy tzv. Visegrádské skupiny. Které čtyři státy tuto skupinu tvoří?", "options": { "A": "Česko, Polsko, Rakousko, Slovinsko.", "B": "Česko, Slovensko, Polsko, Německo.", "C": "Česko, Slovensko, Maďarsko, Polsko.", "D": "Česko, Slovensko, Maďarsko, Rakousko." }, "correct": "C" },
  { "category": "MEZINÁRODNÍ SOUVISLOSTI", "question": "Které město je sídlem Evropského soudu pro lidská práva?", "options": { "A": "Haag.", "B": "Brusel.", "C": "Štrasburk.", "D": "Lucemburk." }, "correct": "C" },
  { "category": "MEZINÁRODNÍ SOUVISLOSTI", "question": "V roce 2007 Česko vstoupilo do schengenského prostoru. Do které z těchto zemí může český občan cestovat bez kontroly na hranicích?", "options": { "A": "Do Turecka.", "B": "Do Německa.", "C": "Do Velké Británie.", "D": "Do Spojených států amerických." }, "correct": "B" },
  { "category": "MEZINÁRODNÍ SOUVISLOSTI", "question": "Česká republika je od 12. března 1999 členem mezinárodní organizace. Vlajku této organizace můžete vidět na obrázku. Jak se tato organizace jmenuje?", "options": { "A": "EU – Evropská unie.", "B": "OSN – Organizace spojených národů.", "C": "NATO – Organizace severoatlantické smlouvy.", "D": "OECD – Organizace pro ekonomickou spolupráci a rozvoj." }, "correct": "C" },
  { "category": "MEZINÁRODNÍ SOUVISLOSTI", "question": "Jaké právo mají v Evropské unii její občané, a tedy i občané České republiky?", "options": { "A": "Právo volit předsedu Evropské komise.", "B": "Právo volit poslance Evropského parlamentu.", "C": "Právo volit eurokomisaře za jednotlivé členské státy.", "D": "Právo hlasovat o přijímání nových států do Evropské unie." }, "correct": "B" },
  { "category": "MEZINÁRODNÍ SOUVISLOSTI", "question": "Evropská komise je výkonný orgán Evropské unie a řídí její politiku. Kolik zástupců má Česko v Evropské komisi?", "options": { "A": "1.", "B": "21.", "C": "81.", "D": "200." }, "correct": "A" },
  { "category": "MEZINÁRODNÍ SOUVISLOSTI", "question": "Česká republika je členem NATO. Které město je sídlem této organizace?", "options": { "A": "Paříž.", "B": "Brusel.", "C": "Ženeva.", "D": "Štrasburk." }, "correct": "B" },
  { "category": "MEZINÁRODNÍ SOUVISLOSTI", "question": "Vlajka na obrázku má dvanáct zlatých hvězd na modrém poli. Která mezinárodní organizace má tuto vlajku?", "options": { "A": "EU – Evropská unie.", "B": "OSN – Organizace spojených národů.", "C": "NATO – Organizace severoatlantické smlouvy.", "D": "OECD – Organizace pro ekonomickou spolupráci a rozvoj." }, "correct": "A" },
  { "category": "STŘEDOVĚK", "question": "Kdo podle pověsti vystoupil na horu Říp?", "options": { "A": "Praotec Čech.", "B": "Přemysl Oráč.", "C": "Kněžna Libuše.", "D": "Vladyka Horymír." }, "correct": "A" },
  { "category": "STŘEDOVĚK", "question": "Která bitva ukončila v roce 1434 husitské náboženské války?", "options": { "A": "Bitva u Lipan.", "B": "Bitva u Slavkova.", "C": "Bitva na Bílé hoře.", "D": "Bitva na Moravském poli." }, "correct": "A" },
  { "category": "STŘEDOVĚK", "question": "Jan Žižka má jezdeckou sochu na vrchu Vítkově v Praze. Kdo byl Jan Žižka?", "options": { "A": "Český král.", "B": "Katolický kněz.", "C": "Husitský bojovník.", "D": "Renesanční umělec." }, "correct": "C" },
  { "category": "STŘEDOVĚK", "question": "Jak se podle pověstí jmenuje kněžna, která předpověděla slávu Prahy?", "options": { "A": "Šárka.", "B": "Vlasta.", "C": "Libuše.", "D": "Ludmila." }, "correct": "C" },
  { "category": "STŘEDOVĚK", "question": "Na začátku července se slaví v České republice dva státní svátky. 5. červenec připomíná příchod bratrů Cyrila a Metoděje na Velkou Moravu. Proč na Moravu Cyril a Metoděj přišli?", "options": { "A": "Založit vinice.", "B": "Šířit křesťanství.", "C": "Založit český stát.", "D": "Sjednotit Čechy a Moravu." }, "correct": "B" },
  { "category": "STŘEDOVĚK", "question": "Jak se jmenoval první český rod knížat a králů, ke kterému patřil i svatý Václav?", "options": { "A": "Jagellonci.", "B": "Přemyslovci.", "C": "Habsburkové.", "D": "Lucemburkové." }, "correct": "B" },
  { "category": "STŘEDOVĚK", "question": "Kalich na obrázku se stal symbolem jednoho významného období v české historii. Toto období připomínají pomníky v českých městech, knihy, filmy, a dokonce jeden státní svátek. Jak se toto období nazývá?", "options": { "A": "Pražské jaro.", "B": "Husitská revoluce.", "C": "Sametová revoluce.", "D": "Stavovské povstání." }, "correct": "B" },
  { "category": "STŘEDOVĚK", "question": "Ze kterého rodu byl slavný český král a římský císař Karel IV.?", "options": { "A": "Z rodu Jagellonců.", "B": "Z rodu Habsburků.", "C": "Z rodu Lucemburků.", "D": "Z rodu Přemyslovců." }, "correct": "C" },
  { "category": "STŘEDOVĚK", "question": "Kdo založil první českou univerzitu?", "options": { "A": "Karel IV.", "B": "Jiří z Poděbrad.", "C": "Přemysl Otakar II.", "D": "Vladislav Jagellonský." }, "correct": "A" },
  { "category": "STŘEDOVĚK", "question": "Dcera krále Přemysla Otakara I. založila ve 13. století v Praze klášter a pečovala o nemocné a chudé. V roce 1989 ji papež prohlásil za svatou. Jak se tato žena jmenovala?", "options": { "A": "Alžběta.", "B": "Anežka.", "C": "Hedvika.", "D": "Markéta." }, "correct": "B" },
  { "category": "NOVOVĚK", "question": "Na přelomu 16. a 17. století se Praha stala kulturním centrem Evropy. Jak se jmenoval panovník, který tehdy v Čechách vládl?", "options": { "A": "Rudolf II.", "B": "Václav II.", "C": "František II.", "D": "Ferdinand II." }, "correct": "A" },
  { "category": "NOVOVĚK", "question": "Který rod začal vládnout Českému království v roce 1526 a vládl až do roku 1918?", "options": { "A": "Jagellonci.", "B": "Přemyslovci.", "C": "Habsburkové.", "D": "Lucemburkové." }, "correct": "C" },
  { "category": "NOVOVĚK", "question": "V roce 1618 se čeští nekatoličtí šlechtici postavili proti císaři. Tato událost začala válku, která se rozšířila téměř po celé Evropě. Jak se tato válka jmenuje?", "options": { "A": "Zimní válka.", "B": "Třicetiletá válka.", "C": "Prusko-rakouská válka.", "D": "Válka o rakouské dědictví." }, "correct": "B" },
  { "category": "NOVOVĚK", "question": "Ve kterém městě se odehrává pověst o Golemovi, kterého stvořil rabi Löw?", "options": { "A": "V Plzni.", "B": "V Praze.", "C": "V Jihlavě.", "D": "V Ostravě." }, "correct": "B" },
  { "category": "NOVOVĚK", "question": "V České republice se 28. března slaví Den učitelů a připomíná se narození „učitele národů“. Koho Češi považují za „učitele národů“?", "options": { "A": "Jana Amose Komenského.", "B": "Karla Havlíčka Borovského.", "C": "Tomáše Garrigua Masaryka.", "D": "Františka Ladislava Čelakovského." }, "correct": "A" },
  { "category": "NOVOVĚK", "question": "V roce 1805 došlo na Moravě k bitvě u Slavkova. Kdo tuto bitvu vyhrál?", "options": { "A": "Císař Alexandr I.", "B": "Císař Napoleon I.", "C": "Generál Kutuzov.", "D": "Generál Wellington." }, "correct": "B" },
  { "category": "NOVOVĚK", "question": "České země byly od roku 1867 součástí Rakouska-Uherska. Kdy přestalo existovat Rakousko-Uhersko?", "options": { "A": "V roce 1914.", "B": "V roce 1918.", "C": "V roce 1938.", "D": "V roce 1948." }, "correct": "B" },
  { "category": "NOVOVĚK", "question": "Jak se říká rozvoji české kultury v 19. století?", "options": { "A": "Jaro národů.", "B": "Normalizace.", "C": "Národní obrození.", "D": "Sametová revoluce." }, "correct": "C" },
  { "category": "NOVOVĚK", "question": "V roce 1618 se protestanté v českých zemích vzbouřili proti císaři, ale o dva roky později byli poraženi. Ve které bitvě císař porazil tyto protestanty?", "options": { "A": "U Lipan.", "B": "Na Vítkově.", "C": "Na Bílé hoře.", "D": "Na Moravském poli." }, "correct": "C" },
  { "category": "NOVOVĚK", "question": "Tato panovnice byla z rodu Habsburků a žila v 18. století. Byla jedinou ženou, která vládla na území Česka. Pomník v Praze na Hradčanech (na obrázku) připomíná 300 let od jejího narození. Kterou českou panovnici představuje tato socha?", "options": { "A": "Císařovnu Marii Terezii.", "B": "Císařovnu Alžbětu (Sisi).", "C": "Královnu Elišku Přemyslovnu.", "D": "Královnu Alžbětu Pomořanskou." }, "correct": "A" },
  { "category": "DĚJINY ČESKOSLOVENSKA DO ROKU 1948", "question": "Co pro Československo znamenala mnichovská dohoda, kterou podepsalo Německo a další tři státy v září 1938?", "options": { "A": "Začátek války.", "B": "Obsazení Prahy.", "C": "Ztrátu pohraničí.", "D": "Ztrátu Slovenska." }, "correct": "C" },
  { "category": "DĚJINY ČESKOSLOVENSKA DO ROKU 1948", "question": "Jak se jmenovala jedna z českých obcí, kterou Němci po atentátu na Reinharda Heydricha v roce 1942 zcela zničili?", "options": { "A": "Lidice.", "B": "Stadice.", "C": "Hrusice.", "D": "Věstonice." }, "correct": "A" },
  { "category": "DĚJINY ČESKOSLOVENSKA DO ROKU 1948", "question": "Jak se jmenoval československý prezident, který žil za 2. světové války ve Velké Británii?", "options": { "A": "Edvard Beneš.", "B": "Klement Gottwald.", "C": "Antonín Zápotocký.", "D": "Tomáš Garrigue Masaryk." }, "correct": "A" },
  { "category": "DĚJINY ČESKOSLOVENSKA DO ROKU 1948", "question": "Které velké armády osvobodily území Československa v roce 1945?", "options": { "A": "Americká a anglická.", "B": "Americká a sovětská.", "C": "Americká a kanadská.", "D": "Americká a francouzská." }, "correct": "B" },
  { "category": "DĚJINY ČESKOSLOVENSKA DO ROKU 1948", "question": "Co se stalo 17. listopadu 1939 na českém území?", "options": { "A": "Nacisté zavřeli vysoké školy.", "B": "Nacisté zcela zničili obec Lidice.", "C": "Armády zemí Varšavské smlouvy obsadily Československo.", "D": "Americká a sovětská armáda osvobodily území Československa." }, "correct": "A" },
  { "category": "DĚJINY ČESKOSLOVENSKA DO ROKU 1948", "question": "Tomáš Garrigue Masaryk byl první prezident Československa a zakladatel moderního československého státu. Na kterém z těchto obrázků je Tomáš Garrigue Masaryk?", "options": { "A": "Obrázek A", "B": "Obrázek B", "C": "Obrázek C", "D": "Obrázek D" }, "correct": "D" },
  { "category": "DĚJINY ČESKOSLOVENSKA DO ROKU 1948", "question": "Jak se jmenoval zastupující říšský protektor, na kterého spáchali Gabčík a Kubiš v roce 1942 v Praze atentát?", "options": { "A": "K. H. Frank.", "B": "Joseph Goebbels.", "C": "Hermann Göring.", "D": "Reinhard Heydrich." }, "correct": "D" },
  { "category": "DĚJINY ČESKOSLOVENSKA DO ROKU 1948", "question": "Který den si Česká republika připomíná konec druhé světové války – Den vítězství?", "options": { "A": "6. července.", "B": "8. května.", "C": "28. října.", "D": "28. září." }, "correct": "B" },
  { "category": "DĚJINY ČESKOSLOVENSKA DO ROKU 1948", "question": "Která historická událost předcházela vzniku Československa v roce 1918?", "options": { "A": "Sametová revoluce.", "B": "První světová válka.", "C": "Druhá světová válka.", "D": "Světová hospodářská krize." }, "correct": "B" },
  { "category": "DĚJINY ČESKOSLOVENSKA DO ROKU 1948", "question": "Kdy vznikl samostatný československý stát?", "options": { "A": "29. září 1938.", "B": "1. ledna 1993.", "C": "28. října 1918.", "D": "8. května 1945." }, "correct": "C" },

      { "category": "DĚJINY ČESKOSLOVENSKA OD ROKU 1948 DO ROKU 1989", "question": "Kdo se stal československým prezidentem v roce 1948 poté, co komunistická strana převzala moc ve státě?", "options": { "A": "Edvard Beneš.", "B": "Klement Gottwald.", "C": "Antonín Zápotocký.", "D": "Tomáš Garrigue Masaryk." }, "correct": "B" },
  { "category": "DĚJINY ČESKOSLOVENSKA OD ROKU 1948 DO ROKU 1989", "question": "Jak se jmenoval student, který se upálil v lednu 1969 v Praze na Václavském náměstí?", "options": { "A": "Jan Palach.", "B": "Jan Opletal.", "C": "Martin Šmíd.", "D": "Václav Sedláček." }, "correct": "A" },
  { "category": "DĚJINY ČESKOSLOVENSKA OD ROKU 1948 DO ROKU 1989", "question": "Která politická strana vládla v Československu od roku 1948 do listopadu roku 1989?", "options": { "A": "Komunistická strana Československa.", "B": "Československá strana socialistická.", "C": "Československá strana lidová.", "D": "Agrární strana." }, "correct": "A" },
  { "category": "DĚJINY ČESKOSLOVENSKA OD ROKU 1948 DO ROKU 1989", "question": "Jak se jmenoval dokument, kterým někteří občané v 70. letech 20. století protestovali proti komunistickému režimu?", "options": { "A": "Poučení z krizového vývoje.", "B": "Několik vět.", "C": "2 000 slov.", "D": "Charta 77." }, "correct": "D" },
  { "category": "DĚJINY ČESKOSLOVENSKA OD ROKU 1948 DO ROKU 1989", "question": "Která významná událost české historie se stala 21. srpna 1968?", "options": { "A": "Začala okupace Československa vojsky Varšavské smlouvy.", "B": "Z Československa se stala federativní republika.", "C": "Na protest proti okupaci se upálil Jan Palach.", "D": "Vznikl samostatný český a slovenský stát." }, "correct": "A" },
  { "category": "DĚJINY ČESKOSLOVENSKA OD ROKU 1948 DO ROKU 1989", "question": "Kdy začala v Československu tzv. sametová revoluce?", "options": { "A": "8. května 1945.", "B": "25. února 1948.", "C": "17. listopadu 1939.", "D": "17. listopadu 1989." }, "correct": "D" },
  { "category": "DĚJINY ČESKOSLOVENSKA OD ROKU 1948 DO ROKU 1989", "question": "Rok 1989 byl rokem velkých společenských změn. Václav Havel byl ještě v prvních měsících roku 1989 z politických důvodů ve vězení, ale na konci roku 1989 byl zvolen do významné politické funkce. Která funkce to byla?", "options": { "A": "Předseda vlády.", "B": "Prezident republiky.", "C": "Ministr zahraničních věcí.", "D": "Předseda Národního shromáždění." }, "correct": "B" },
  { "category": "DĚJINY ČESKOSLOVENSKA OD ROKU 1948 DO ROKU 1989", "question": "Jaký program měla protikomunistická občanská iniciativa Charta 77?", "options": { "A": "Ozbrojený boj.", "B": "Uměleckou tvorbu.", "C": "Ochranu lidských práv.", "D": "Vydávání české literatury v zahraničí." }, "correct": "C" },
  { "category": "DĚJINY ČESKOSLOVENSKA OD ROKU 1948 DO ROKU 1989", "question": "V letech 1949 až 1961 někteří odpůrci komunistického režimu pracovali jako političtí vězni v uranových dolech. U kterého z těchto měst byly uranové doly?", "options": { "A": "Břeclav.", "B": "Znojmo.", "C": "Příbram.", "D": "Litoměřice." }, "correct": "C" },
  { "category": "DĚJINY ČESKOSLOVENSKA OD ROKU 1948 DO ROKU 1989", "question": "Jak se jmenovala česká politička odsouzená v roce 1950 v politickém procesu k trestu smrti?", "options": { "A": "Marie Majerová.", "B": "Zdena Mašínová.", "C": "Milada Horáková.", "D": "Marta Gottwaldová." }, "correct": "C" },
  { "category": "DĚJINY ČESKA OD ROKU 1989", "question": "Kdy vznikla samostatná Česká republika?", "options": { "A": "1. ledna 1993.", "B": "28. října 1918.", "C": "8. května 1945.", "D": "17. listopadu 1989." }, "correct": "A" },
  { "category": "DĚJINY ČESKA OD ROKU 1989", "question": "Česká republika je od roku 1999 členem NATO. K čemu tato organizace slouží?", "options": { "A": "K vědecké spolupráci.", "B": "K vojenské spolupráci.", "C": "K rozvojové spolupráci.", "D": "K ekonomické spolupráci." }, "correct": "B" },
  { "category": "DĚJINY ČESKA OD ROKU 1989", "question": "Kdy Česká republika vstoupila do Evropské unie?", "options": { "A": "V roce 1989.", "B": "V roce 1993.", "C": "V roce 1999.", "D": "V roce 2004." }, "correct": "D" },
  { "category": "DĚJINY ČESKA OD ROKU 1989", "question": "Které dva státy vznikly po rozpadu Československa v roce 1993?", "options": { "A": "Čechy a Morava.", "B": "Česká republika a Slovenská republika.", "C": "Protektorát Čechy a Morava a Slovenská republika.", "D": "Česká socialistická republika a Slovenská socialistická republika." }, "correct": "B" },
  { "category": "DĚJINY ČESKA OD ROKU 1989", "question": "Památník na obrázku připomíná událost, kterou začala tzv. sametová revoluce v roce 1989. Kde v Praze se tento památník nachází?", "options": { "A": "V Celetné ulici.", "B": "Na Národní třídě.", "C": "Ve Vodičkově ulici.", "D": "V ulici Milady Horákové." }, "correct": "B" },
  { "category": "DĚJINY ČESKA OD ROKU 1989", "question": "Kterou z těchto funkcí vykonával Václav Havel?", "options": { "A": "Funkci předsedy vlády.", "B": "Funkci předsedy Senátu.", "C": "Funkci prezidenta republiky.", "D": "Funkci předsedy Poslanecké sněmovny." }, "correct": "C" },
  { "category": "DĚJINY ČESKA OD ROKU 1989", "question": "Který den se slaví státní svátek Den obnovy samostatného českého státu?", "options": { "A": "28. září.", "B": "1. ledna.", "C": "28. října.", "D": "17. listopadu." }, "correct": "B" },
  { "category": "DĚJINY ČESKA OD ROKU 1989", "question": "Kdo se stal českým prezidentem po Václavu Havlovi v roce 2003?", "options": { "A": "Jan Švejnar.", "B": "Václav Klaus.", "C": "Miloš Zeman.", "D": "Vladimír Špidla." }, "correct": "B" },
  { "category": "DĚJINY ČESKA OD ROKU 1989", "question": "Kdo se stal českým prezidentem po Miloši Zemanovi v roce 2023?", "options": { "A": "Petr Fiala.", "B": "Petr Pavel.", "C": "Andrej Babiš.", "D": "Miloš Vystrčil." }, "correct": "B" },
  { "category": "DĚJINY ČESKA OD ROKU 1989", "question": "Kdy odešli z území Československa poslední sovětští vojáci, jejichž armáda obsadila Československo v roce 1968?", "options": { "A": "V roce 1989.", "B": "V roce 1991.", "C": "V roce 1993.", "D": "V roce 2004." }, "correct": "B" },
  { "category": "VÝZNAMNÉ OSOBNOSTI OD 19. STOLETÍ DO SOUČASNOSTI", "question": "Které z těchto hudebních děl složil Antonín Dvořák?", "options": { "A": "Má vlast.", "B": "Z Nového světa.", "C": "Prodaná nevěsta.", "D": "Česká mše vánoční." }, "correct": "B" },
  { "category": "VÝZNAMNÉ OSOBNOSTI OD 19. STOLETÍ DO SOUČASNOSTI", "question": "Jak se jmenuje hlavní postava nejznámějšího románu Jaroslava Haška?", "options": { "A": "Markéta Lazarová.", "B": "Josef Švejk.", "C": "Babička.", "D": "Josef K." }, "correct": "B" },
  { "category": "VÝZNAMNÉ OSOBNOSTI OD 19. STOLETÍ DO SOUČASNOSTI", "question": "Který český spisovatel získal Nobelovu cenu za literaturu?", "options": { "A": "Franz Kafka.", "B": "Jaroslav Hašek.", "C": "Jaroslav Seifert.", "D": "Bohumil Hrabal." }, "correct": "C" },
  { "category": "VÝZNAMNÉ OSOBNOSTI OD 19. STOLETÍ DO SOUČASNOSTI", "question": "Který slavný český režisér žil v USA a dostal dvě filmové ceny Oscar?", "options": { "A": "Jan Svěrák.", "B": "Jiří Menzel.", "C": "Jan Hřebejk.", "D": "Miloš Forman." }, "correct": "D" },
  { "category": "VÝZNAMNÉ OSOBNOSTI OD 19. STOLETÍ DO SOUČASNOSTI", "question": "Mendelova univerzita v Brně se jmenuje po Gregoru Johannu Mendelovi. Čím se tento muž zabýval?", "options": { "A": "Architekturou.", "B": "Klasickou hudbou.", "C": "Historií a politikou.", "D": "Pokusy s rostlinami." }, "correct": "D" },
  { "category": "VÝZNAMNÉ OSOBNOSTI OD 19. STOLETÍ DO SOUČASNOSTI", "question": "Které slovo jako první na světě použil český spisovatel Karel Čapek ve svém dramatu R.U.R.?", "options": { "A": "Supernova.", "B": "Astronaut.", "C": "Skafandr.", "D": "Robot." }, "correct": "D" },
  { "category": "VÝZNAMNÉ OSOBNOSTI OD 19. STOLETÍ DO SOUČASNOSTI", "question": "Jak se jmenoval český podnikatel a zakladatel významné strojírenské firmy v Plzni?", "options": { "A": "Emil Škoda.", "B": "Tomáš Baťa.", "C": "Emil Kolben.", "D": "Václav Laurin." }, "correct": "A" },
  { "category": "VÝZNAMNÉ OSOBNOSTI OD 19. STOLETÍ DO SOUČASNOSTI", "question": "Který český vynálezce v 19. století uvedl do provozu první veřejné elektrické osvětlení a první elektrickou tramvaj v českých zemích?", "options": { "A": "Josef Ressel.", "B": "Otto Wichterle.", "C": "František Křižík.", "D": "Jaroslav Heyrovský." }, "correct": "C" },
  { "category": "VÝZNAMNÉ OSOBNOSTI OD 19. STOLETÍ DO SOUČASNOSTI", "question": "Jak se jmenuje literární dílo, které napsal Karel Hynek Mácha?", "options": { "A": "Máj.", "B": "Babička.", "C": "F. L. Věk.", "D": "Povídky malostranské." }, "correct": "A" },
  { "category": "VÝZNAMNÉ OSOBNOSTI OD 19. STOLETÍ DO SOUČASNOSTI", "question": "Ve kterém sportovním odvětví se proslavil Emil Zátopek?", "options": { "A": "V lehké atletice.", "B": "V cyklistice.", "C": "Ve fotbale.", "D": "V hokeji." }, "correct": "A" },
  { "category": "UMĚNÍ OD STŘEDOVĚKU DO SOUČASNOSTI", "question": "Dům U Černé Matky Boží je významnou stavbou kubistické architektury v Praze. Stavbu navrhl Josef Gočár. V budově je stálá výstava Český kubismus a kavárna. Na kterém obrázku je Dům U Černé Matky Boží?", "options": { "A": "Obrázek A", "B": "Obrázek B", "C": "Obrázek C", "D": "Obrázek D" }, "correct": "D" },
  { "category": "UMĚNÍ OD STŘEDOVĚKU DO SOUČASNOSTI", "question": "Na kterém obrázku jsou Pražský hrad s gotickým Chrámem svatého Víta – symboly české státnosti?", "options": { "A": "Obrázek A", "B": "Obrázek B", "C": "Obrázek C", "D": "Obrázek D" }, "correct": "A" },
  { "category": "UMĚNÍ OD STŘEDOVĚKU DO SOUČASNOSTI", "question": "Na kterém obrázku je Národní divadlo v Praze?", "options": { "A": "Obrázek A", "B": "Obrázek B", "C": "Obrázek C", "D": "Obrázek D" }, "correct": "B" },
  { "category": "UMĚNÍ OD STŘEDOVĚKU DO SOUČASNOSTI", "question": "Na kterém obrázku je hrad Karlštejn, který založil Karel IV.?", "options": { "A": "Obrázek A", "B": "Obrázek B", "C": "Obrázek C", "D": "Obrázek D" }, "correct": "C" },
  { "category": "UMĚNÍ OD STŘEDOVĚKU DO SOUČASNOSTI", "question": "Na kterém obrázku je Petřínská rozhledna v Praze?", "options": { "A": "Obrázek A", "B": "Obrázek B", "C": "Obrázek C", "D": "Obrázek D" }, "correct": "B" },
  { "category": "UMĚNÍ OD STŘEDOVĚKU DO SOUČASNOSTI", "question": "Na obrázku je česká památka zapsaná v UNESCO. Jak se tato památka jmenuje?", "options": { "A": "Zámek Litomyšl.", "B": "Zámek Český Krumlov.", "C": "Chrám sv. Barbory v Kutné Hoře.", "D": "Kostel sv. Jana Nepomuckého na Zelené hoře." }, "correct": "D" },
  { "category": "UMĚNÍ OD STŘEDOVĚKU DO SOUČASNOSTI", "question": "Koho představuje tato socha na pražském Vítkově?", "options": { "A": "Jana Žižku.", "B": "Miroslava Tyrše.", "C": "Jiřího z Poděbrad.", "D": "Tomáše Garrigua Masaryka." }, "correct": "A" },
  { "category": "UMĚNÍ OD STŘEDOVĚKU DO SOUČASNOSTI", "question": "Vila Tugendhat (na obrázku) je na seznamu světového kulturního dědictví UNESCO. Kde se nachází?", "options": { "A": "V Olomouci.", "B": "V Liberci.", "C": "V Praze.", "D": "V Brně." }, "correct": "D" },
  { "category": "UMĚNÍ OD STŘEDOVĚKU DO SOUČASNOSTI", "question": "Orloj jsou středověké hodiny na věži. Na kterém obrázku je pražský orloj?", "options": { "A": "Obrázek A", "B": "Obrázek B", "C": "Obrázek C", "D": "Obrázek D" }, "correct": "C" },
  { "category": "UMĚNÍ OD STŘEDOVĚKU DO SOUČASNOSTI", "question": "Na obrázku je známá pražská budova ve stylu secese. K čemu slouží tato budova?", "options": { "A": "Je to banka.", "B": "Je to letiště.", "C": "Je to nádraží.", "D": "Je to parlament." }, "correct": "C" },
                                                                 
];



